name = "ai-chat-worker"
main = "src/index.ts"
compatibility_date = "2024-08-09"
compatibility_flags = ["nodejs_compat"]

# 生产环境变量
[env.production.vars]
CORS_ORIGIN = "https://hinatayuan.github.io"
ENVIRONMENT = "production"

# 开发环境变量
[env.development.vars]
CORS_ORIGIN = "http://localhost:3000"
ENVIRONMENT = "development"

# 默认环境变量
[vars]
CORS_ORIGIN = "*"
ENVIRONMENT = "development"

# Secrets (通过 wrangler secret 命令设置)
# wrangler secret put OPENAI_API_KEY

# 限制配置
[limits]
cpu_ms = 30000